jasperserver:
  build: .
  ports:
  - "8080:8080"
  environment:
  - DB_TYPE=mysql
  - DB_HOST=db
  - DB_USER=root
  - DB_PASSWORD=mysql
  links:
  - mysql:db
mysql:
  image: mysql
  environment:
  - MYSQL_ROOT_PASSWORD=mysql