jasperserver:
  build: .
  ports:
  - "8080:8080"
  environment:
  - DB_TYPE=postgresql
  - DB_HOST=db
  - DB_USER=postgres
  - DB_PASSWORD=postgres
  links:
  - postgres:db
postgres:
  image: postgres
  environment:
  - POSTGRES_PASSWORD=postgres